examples/v1.10.1/values.yaml
Endpoint configuration to identity microservice is added.
=> Update value.yaml to reflect configuration

examples/v1.10.1/database.yaml
Add database for new microservice(board/file-manager). 
Delete database for deprecated microservice(power-scheduler, cost-savings...)
=> Add board/file-manager service, Delete deprecated microservices

examples/v1.10.5/README.md, examples/v1.10.5/on-premise/additional/eco/docs.yaml, examples/v1.10.5/on-premise/additional/eco/spacectl.yaml, examples/v1.10.5/on-premise/additional/ingress/assets-ingress.yaml, examples/v1.10.5/on-premise/additional/ingress/console-ingress.yaml, examples/v1.10.5/on-premise/additional/ingress/docs-ingress.yaml, examples/v1.10.5/on-premise/additional/ingress/grpc-ingress.yaml, examples/v1.10.5/on-premise/pre-install/shared.yaml, examples/v1.10.5/on-premise/spaceone-domain/domain.yaml, examples/v1.10.5/on-premise/spaceone/database.yaml, examples/v1.10.5/on-premise/spaceone/frontend.yaml, examples/v1.10.5/on-premise/spaceone/values.yaml
Helm chart 1.10.5 has been added for on-premises environments.
=> feat: support on-prem environment

README.md
While installing cloudforet according to the guide, users need to download the yaml file.
But, Currently there is only the location of the yaml file, No way to download file.
So i added this content.
=> Docs: Download yaml with wget

README.md
url to download raw file is wrong, not GeunjeLEE.
=> fix: wrong url to download raw file

README.md, examples/values/set_opentelemetry_values.yaml
=> Add set OTel example

examples/initializer.yaml
Change spaceone-initializer.yaml file contents for release-1.12
=> feat: change spaceone-initializer yaml file

README.md
=> feat: modify pod list recently

README.md
Change wrong  helm install name.
Remove identity required text. (Option is changed.)
=> feat: change wrong contents

charts/k8s-monitoring/values.yaml
Solve invalid type. Expected: array, given: string
=> Solve invalid type. Expected: array, given: string

.github/workflows/publish.yaml
=> Fix indentation

.github/workflows/publish.yaml
Fix chart_name and chart_version's newline
=> Fix chart_name and chart_version's newline

.github/workflows/publish.yaml
Add helm packaging and publish to gh-pages
=> Add helm packaging and publish to gh-pages

charts/k8s-monitoring/values.yaml
=> Fix test profiles

charts/k8s-monitoring/values.yaml
=> Fix test receiver.transforms

charts/k8s-monitoring/values.yaml
Update opencost prometheus url
=> Update opencost prometheus url

charts/k8s-monitoring/values.yaml
Delete grafana-agent's node_selector
=> Delete grafana-agent's node_selector

charts/k8s-monitoring/Chart.yaml, charts/k8s-monitoring/values.yaml
Fix grafana/k8s-monitoring version to 0.13.5
=> Fix grafana/k8s-monitoring version to 0.13.5

index.yaml
=> Add spaceone 1.12.12

index.yaml
Update sha256sum about spaceone 1.12.12
=> Update sha256sum about spaceone 1.12.12
